/* Generated by Curium v5.0 compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Global Args for std::process */
int __curium_argc;
char** __curium_argv;

/* ── Curium String Runtime ── */
typedef struct curium_string_t {
    char* data;
    size_t length;
    size_t capacity;
} curium_string_t;

static curium_string_t* curium_string_from(const char* s) {
    curium_string_t* str = (curium_string_t*)malloc(sizeof(curium_string_t));
    str->length = strlen(s);
    str->capacity = str->length + 1;
    str->data = (char*)malloc(str->capacity);
    memcpy(str->data, s, str->capacity);
    return str;
}

static void curium_string_free(curium_string_t* s) {
    if (s) { free(s->data); free(s); }
}

/* ── Curium Builtins ── */
static void curium_print(curium_string_t* s) {
    if (s) printf("%s", s->data);
}

static void curium_println(curium_string_t* s) {
    if (s) printf("%s\n", s->data);
}

typedef struct Token Token;
typedef struct AstNode AstNode;
curium_string_t* token_kind_name(int32_t kind);
void print_token(Token tok);
bool is_alpha(int32_t ch);
bool is_digit(int32_t ch);
bool is_whitespace(int32_t ch);
void emit_c_preamble(void);
void emit_c_type(curium_string_t* type_name);
int32_t compile_source(curium_string_t* source);

struct Token {
    int32_t kind;
    curium_string_t* value;
    int32_t line;
};

int main(int argc, char** argv) {
    __curium_argc = argc;
    __curium_argv = argv;
    curium_println(curium_string_from("Curium Self-Hosting Compiler v0.1.0"));
    curium_println(curium_string_from("==================================="));
    curium_println(curium_string_from(""));
    curium_println(curium_string_from("Bootstrap compiler structure:"));
    curium_println(curium_string_from("  1. Lexer   — Tokenizes .cm source into token stream"));
    curium_println(curium_string_from("  2. Parser  — Builds Abstract Syntax Tree (AST)"));
    curium_println(curium_string_from("  3. Codegen — Emits C11 source code"));
    curium_println(curium_string_from(""));
    Token tok_fn = (Token) { .kind = 40, .value = curium_string_from("fn"), .line = 1 };
    Token tok_main = (Token) { .kind = 1, .value = curium_string_from("main"), .line = 1 };
    Token tok_lparen = (Token) { .kind = 10, .value = curium_string_from("("), .line = 1 };
    Token tok_rparen = (Token) { .kind = 11, .value = curium_string_from(")"), .line = 1 };
    Token tok_arrow = (Token) { .kind = 31, .value = curium_string_from("->"), .line = 1 };
    Token tok_i32 = (Token) { .kind = 50, .value = curium_string_from("i32"), .line = 1 };
    curium_println(curium_string_from("Token stream for 'fn main() -> i32':"));
    print_token(tok_fn);
    print_token(tok_main);
    print_token(tok_lparen);
    print_token(tok_rparen);
    print_token(tok_arrow);
    print_token(tok_i32);
    curium_println(curium_string_from(""));
    curium_println(curium_string_from("Bootstrap verification:"));
    curium_println(curium_string_from("  Stage 1: cm build compiler.cm -o compiler_v1 --emit-c"));
    curium_println(curium_string_from("  Stage 2: compiler_v1 recompiles compiler.cm"));
    curium_println(curium_string_from("  Stage 3: Verify deterministic output (diff)"));
    curium_println(curium_string_from(""));
    curium_println(curium_string_from("Self-hosting bootstrap path initialized successfully."));
    return 0;
}

curium_string_t* token_kind_name(int32_t kind) {
    if ((kind == 0)) {
        return curium_string_from("EOF");
    }
    if ((kind == 1)) {
        return curium_string_from("Identifier");
    }
    if ((kind == 2)) {
        return curium_string_from("Number");
    }
    if ((kind == 3)) {
        return curium_string_from("String");
    }
    if ((kind == 10)) {
        return curium_string_from("LParen");
    }
    if ((kind == 11)) {
        return curium_string_from("RParen");
    }
    if ((kind == 12)) {
        return curium_string_from("LBrace");
    }
    if ((kind == 13)) {
        return curium_string_from("RBrace");
    }
    if ((kind == 14)) {
        return curium_string_from("Semi");
    }
    if ((kind == 15)) {
        return curium_string_from("Comma");
    }
    if ((kind == 16)) {
        return curium_string_from("Colon");
    }
    if ((kind == 20)) {
        return curium_string_from("Plus");
    }
    if ((kind == 21)) {
        return curium_string_from("Minus");
    }
    if ((kind == 22)) {
        return curium_string_from("Star");
    }
    if ((kind == 23)) {
        return curium_string_from("Slash");
    }
    if ((kind == 24)) {
        return curium_string_from("Equal");
    }
    if ((kind == 25)) {
        return curium_string_from("EqualEqual");
    }
    if ((kind == 26)) {
        return curium_string_from("BangEqual");
    }
    if ((kind == 27)) {
        return curium_string_from("Lt");
    }
    if ((kind == 28)) {
        return curium_string_from("Gt");
    }
    if ((kind == 29)) {
        return curium_string_from("LtEq");
    }
    if ((kind == 30)) {
        return curium_string_from("GtEq");
    }
    if ((kind == 31)) {
        return curium_string_from("Arrow");
    }
    if ((kind == 40)) {
        return curium_string_from("KwFn");
    }
    if ((kind == 41)) {
        return curium_string_from("KwLet");
    }
    if ((kind == 42)) {
        return curium_string_from("KwMut");
    }
    if ((kind == 43)) {
        return curium_string_from("KwReturn");
    }
    if ((kind == 44)) {
        return curium_string_from("KwIf");
    }
    if ((kind == 45)) {
        return curium_string_from("KwElse");
    }
    if ((kind == 46)) {
        return curium_string_from("KwWhile");
    }
    if ((kind == 47)) {
        return curium_string_from("KwStruct");
    }
    if ((kind == 50)) {
        return curium_string_from("KwI32");
    }
    if ((kind == 51)) {
        return curium_string_from("KwString");
    }
    if ((kind == 55)) {
        return curium_string_from("KwPrintln");
    }
    return curium_string_from("Unknown");
}

void print_token(Token tok) {
    curium_println(token_kind_name(tok.kind));
}

bool is_alpha(int32_t ch) {
    if ((ch >= 65)) {
        if ((ch <= 90)) {
            return true;
        }
    }
    if ((ch >= 97)) {
        if ((ch <= 122)) {
            return true;
        }
    }
    if ((ch == 95)) {
        return true;
    }
    return false;
}

bool is_digit(int32_t ch) {
    if ((ch >= 48)) {
        if ((ch <= 57)) {
            return true;
        }
    }
    return false;
}

bool is_whitespace(int32_t ch) {
    if ((ch == 32)) {
        return true;
    }
    if ((ch == 9)) {
        return true;
    }
    if ((ch == 10)) {
        return true;
    }
    if ((ch == 13)) {
        return true;
    }
    return false;
}

struct AstNode {
    int32_t kind;
    curium_string_t* name;
    int32_t line;
};

void emit_c_preamble(void) {
    curium_println(curium_string_from("/* Generated by Curium Self-Hosting Compiler v0.1.0 */"));
    curium_println(curium_string_from("#include <stdio.h>"));
    curium_println(curium_string_from("#include <stdlib.h>"));
    curium_println(curium_string_from("#include <stdint.h>"));
    curium_println(curium_string_from("#include <stdbool.h>"));
    curium_println(curium_string_from("#include <string.h>"));
    curium_println(curium_string_from(""));
    curium_println(curium_string_from("/* -- Curium String Runtime -- */"));
    curium_println(curium_string_from("typedef struct curium_string_t {"));
    curium_println(curium_string_from("    char* data;"));
    curium_println(curium_string_from("    size_t length;"));
    curium_println(curium_string_from("    size_t capacity;"));
    curium_println(curium_string_from("} curium_string_t;"));
    curium_println(curium_string_from(""));
    curium_println(curium_string_from("static curium_string_t* curium_string_from(const char* s) {"));
    curium_println(curium_string_from("    curium_string_t* str = (curium_string_t*)malloc(sizeof(curium_string_t));"));
    curium_println(curium_string_from("    str->length = strlen(s);"));
    curium_println(curium_string_from("    str->capacity = str->length + 1;"));
    curium_println(curium_string_from("    str->data = (char*)malloc(str->capacity);"));
    curium_println(curium_string_from("    memcpy(str->data, s, str->capacity);"));
    curium_println(curium_string_from("    return str;"));
    curium_println(curium_string_from("}"));
    curium_println(curium_string_from(""));
    curium_println(curium_string_from("static void curium_println(curium_string_t* s) {"));
    curium_println(curium_string_from("    if (s) printf(\"%s\\n\", s->data);"));
    curium_println(curium_string_from("}"));
    curium_println(curium_string_from(""));
    curium_println(curium_string_from("static void curium_print(curium_string_t* s) {"));
    curium_println(curium_string_from("    if (s) printf(\"%s\", s->data);"));
    curium_println(curium_string_from("}"));
    curium_println(curium_string_from(""));
}

void emit_c_type(curium_string_t* type_name) {
    curium_println(curium_string_from("int32_t"));
}

int32_t compile_source(curium_string_t* source) {
    curium_println(curium_string_from("// Phase 1: Lexing..."));
    curium_println(curium_string_from("// Phase 2: Parsing..."));
    curium_println(curium_string_from("// Phase 3: Code Generation..."));
    emit_c_preamble();
    curium_println(curium_string_from("// Compilation complete."));
    return 0;
}

