/* Generated by Curium v5.0 compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Global Args for std::process */
int __curium_argc;
char** __curium_argv;

/* ── Curium String Runtime ── */
typedef struct curium_string_t {
    char* data;
    size_t length;
    size_t capacity;
} curium_string_t;

static curium_string_t* curium_string_from(const char* s) {
    curium_string_t* str = (curium_string_t*)malloc(sizeof(curium_string_t));
    str->length = strlen(s);
    str->capacity = str->length + 1;
    str->data = (char*)malloc(str->capacity);
    memcpy(str->data, s, str->capacity);
    return str;
}

static void curium_string_free(curium_string_t* s) {
    if (s) { free(s->data); free(s); }
}

/* ── Curium Dynamic Type ── */
typedef struct curium_dyn_t {
    enum { DYN_INT, DYN_FLOAT, DYN_STRING, DYN_PTR, DYN_NULL } tag;
    union {
        int64_t int_val;
        double float_val;
        curium_string_t* string_val;
        void* ptr_val;
    };
} curium_dyn_t;

/* ── Curium Builtins ── */
static void curium_print(curium_string_t* s) {
    if (s) printf("%s", s->data);
}

static void curium_println(curium_string_t* s) {
    if (s) printf("%s\n", s->data);
}

typedef struct Vector Vector;
curium_string_t** args(void);
int32_t env_argc(void);
void process_exit(int32_t code);
curium_string_t* read_to_string(curium_string_t* path);
int32_t write_string(curium_string_t* path, curium_string_t* content);
curium_string_t* concat(curium_string_t* a, curium_string_t* b);
curium_string_t* int_to_string(int32_t n);
Vector* vec_new(void);
void vec_push(Vector* v, curium_dyn_t element);
curium_dyn_t vec_get(Vector* v, int32_t index);
int32_t vec_len(Vector* v);
curium_dyn_t dyn_int(int32_t n);

curium_string_t** args(void) {
    curium_string_t** args;
    /* c { } verbatim */
    
            args = (curium_string_t**)malloc(__curium_argc * sizeof(curium_string_t*));
            for (int i = 0; i < __curium_argc; i++) {
                args[i] = curium_string_from(__curium_argv[i]);
            }
        
    return args;
}

int32_t env_argc(void) {
    int32_t count = 0;
    /* c { } verbatim */
    
            count = __curium_argc;
        
    return count;
}

void process_exit(int32_t code) {
    /* c { } verbatim */
    
            exit(code);
        
}

curium_string_t* read_to_string(curium_string_t* path) {
    curium_string_t* result;
    /* c { } verbatim */
    
            FILE* f = fopen(path->data, "rb");
            if (!f) {
                result = curium_string_from("");
            } else {
                fseek(f, 0, SEEK_END);
                long fsize = ftell(f);
                fseek(f, 0, SEEK_SET);
    
                char* string_buf = (char*)malloc(fsize + 1);
                fread(string_buf, 1, fsize, f);
                fclose(f);
                string_buf[fsize] = 0;
    
                result = curium_string_from(string_buf);
                free(string_buf);
            }
        
    return result;
}

int32_t write_string(curium_string_t* path, curium_string_t* content) {
    int32_t success = 0;
    /* c { } verbatim */
    
            FILE* f = fopen(path->data, "wb");
            if (f) {
                size_t written = fwrite(content->data, 1, content->length, f);
                fclose(f);
                if (written == content->length) {
                    success = 1;
                }
            }
        
    return success;
}

curium_string_t* concat(curium_string_t* a, curium_string_t* b) {
    curium_string_t* result;
    /* c { } verbatim */
    
            size_t len_a = a->length;
            size_t len_b = b->length;
            curium_string_t* new_str = (curium_string_t*)malloc(sizeof(curium_string_t));
            new_str->length = len_a + len_b;
            new_str->capacity = new_str->length + 1;
            new_str->data = (char*)malloc(new_str->capacity);
            memcpy(new_str->data, a->data, len_a);
            memcpy(new_str->data + len_a, b->data, len_b);
            new_str->data[new_str->length] = '\0';
            result = new_str;
        
    return result;
}

curium_string_t* int_to_string(int32_t n) {
    curium_string_t* result;
    /* c { } verbatim */
    
            char buf[32];
            snprintf(buf, sizeof(buf), "%d", n);
            result = curium_string_from(buf);
        
    return result;
}

struct Vector {
    curium_dyn_t data;
    int32_t length;
    int32_t capacity;
};

Vector* vec_new(void) {
    Vector* v;
    /* c { } verbatim */
    
            struct Vector* vector = (struct Vector*)malloc(sizeof(struct Vector));
            vector->capacity = 4;
            vector->length = 0;
            vector->data.tag = DYN_PTR;
            vector->data.ptr_val = malloc(vector->capacity * sizeof(curium_dyn_t));
            v = vector;
        
    return v;
}

void vec_push(Vector* v, curium_dyn_t element) {
    /* c { } verbatim */
    
            struct Vector* vector = v;
            if (vector->length >= vector->capacity) {
                vector->capacity *= 2;
                vector->data.ptr_val = realloc(vector->data.ptr_val, vector->capacity * sizeof(curium_dyn_t));
            }
            curium_dyn_t* arr = (curium_dyn_t*)vector->data.ptr_val;
            arr[vector->length] = element;
            vector->length += 1;
        
}

curium_dyn_t vec_get(Vector* v, int32_t index) {
    curium_dyn_t result;
    /* c { } verbatim */
    
            struct Vector* vector = v;
            curium_dyn_t* arr = (curium_dyn_t*)vector->data.ptr_val;
            if (index >= 0 && index < vector->length) {
                result = arr[index];
            } else {
                result.tag = DYN_NULL;
            }
        
    return result;
}

int32_t vec_len(Vector* v) {
    int32_t len;
    /* c { } verbatim */
    
            struct Vector* vector = v;
            len = vector->length;
        
    return len;
}

curium_dyn_t dyn_int(int32_t n) {
    curium_dyn_t d;
    /* c { } verbatim */
    
            d.tag = DYN_INT;
            d.int_val = n;
        
    return d;
}

int main(int argc, char** argv) {
    __curium_argc = argc;
    __curium_argv = argv;
    int32_t argc_count = env_argc();
    curium_string_t** args_list = args();
    curium_println(curium_string_from("Testing Vector..."));
    Vector* v = vec_new();
    curium_dyn_t n1 = dyn_int(10);
    curium_dyn_t n2 = dyn_int(20);
    vec_push(v, n1);
    vec_push(v, n2);
    int32_t len = vec_len(v);
    curium_println(curium_string_from("Testing File I/O..."));
    curium_string_t* test_file = curium_string_from("test_artifacts.txt");
    write_string(test_file, curium_string_from("Hello from Curium Standard Library!"));
    curium_string_t* content = read_to_string(test_file);
    curium_println(curium_string_from("Testing Strings..."));
    curium_string_t* joined = concat(curium_string_from("Hello "), curium_string_from("World"));
    curium_string_t* num_str = int_to_string(42);
    curium_println(curium_string_from("UC-031 to UC-034: Standard Library — OK"));
    return 0;
}

